name: Docker Image CI for GHCR

on: push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: npm install
        run: npm ci
      - name: run the unit tests
        run: npm test
      - name: Publish the image to github container registry
        run: |
          echo ${{ secrets.GHCR_TOKEN }} | docker login --username ${{ github.actor }} --password-stdin ghcr.io
          docker build -t ghcr.io/saicharan1505/arithmetic-service:latest --file Dockerfile .
          docker push ghcr.io/saicharan1505/arithmetic-service:latest
      - name: Publish the image to azure container registry
        run: |
          echo ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }} | docker login --username charanpracticum15 --password-stdin charanpracticum15.azurecr.io
          docker tag ghcr.io/saicharan1505/arithmetic-service:latest charanpracticum15.azurecr.io/arithmetic-service:latest
          docker push charanpracticum15.azurecr.io/arithmetic-service:latest
